source 'https://rubygems.org'

gem 'rails', '4.2.3'
gem 'sqlite3'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'wisper', '~> 2.0.0.rc1'
gem 'virtus', '~> 1.0.5'
gem 'delayed_job', '~> 4.0.6'
gem 'delayed_job_active_record', '~> 4.0.3'
gem 'interactor', '~> 3.1.0'

group :development do
  gem 'guard', '~> 2.12.8', require: false
  gem 'guard-rspec', '~> 4.6.1', require: false
end

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem 'rspec-rails', '~> 3.3'
  gem 'capybara', '~> 2.4.4'
  gem 'wisper-rspec', '~> 0.0.2', require: false
  gem 'rspec-virtus', '~> 1.0.2'
end

group :test do
  gem 'shoulda-matchers', '~> 2.8.0', require: false
end

group :doc do
  gem 'sdoc', '~> 0.4.0'
end
